name: test on macos

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.9.x, 12.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
